### ISSUE TITLE
Specification of mirror in jqassistant.yml should be enough in isolated environments

### ISSUE THREAD

**Issue by SebastianWendorf** [jQAssistant/jqa-core-framework#86]
### Task Description
Currently it's necessary to specify a mirror URL twice in the jqassistant.yml, when configuring a mirror for Maven Central in environments where direct access is closed off.
This should be simplyfied in a way that assumes Maven Central as a default.

### Definition of Done for the Implementers
_Remove this hint: these checkboxes can be checked like this: [x]_
- [ ] We got a final feedback from the reporting user (_if applicable_)
- [ ] Unittests have been written (_if applicable_)
- [ ] Integration tests have been written (_if applicable_)
- [ ] Test coverage is the same or even better then before (_if applicable_)
- [ ] Documentation has been written (_if applicable_)
- [ ] Added a note on the new feature to the release notes (_if applicable_)
